# Generated by Django 3.1.2 on 2020-11-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Defects',
            fields=[
                ('defect_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('creator', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('team_area', models.CharField(max_length=1000)),
                ('created_dt', models.DateField()),
                ('modified_dt', models.DateField()),
                ('filed_against', models.CharField(max_length=1000)),
            ],
        ),
    ]
