# Generated by Django 3.1.3 on 2020-11-07 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabrics',
            fields=[
                ('fabric_ip', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('fabric_ip_ping', models.BooleanField(default=False)),
                ('fabric_credentials', models.CharField(max_length=200)),
                ('fabric_type', models.CharField(max_length=200)),
                ('fabric_primary', models.CharField(max_length=200)),
                ('fabric_primary_port', models.CharField(default=0, max_length=10)),
                ('fabric_vsan_id', models.CharField(default=0, max_length=10)),
                ('fabric_serial', models.CharField(max_length=200)),
                ('fabric_location', models.CharField(max_length=200)),
                ('fabric_lab', models.CharField(max_length=200)),
                ('fabric_storwise', models.CharField(max_length=1000)),
                ('fabric_ds8k', models.CharField(max_length=1000)),
                ('fabric_emc_vmax', models.CharField(max_length=1000)),
                ('fabric_emc_vnx', models.CharField(max_length=1000)),
                ('fabric_hitachi', models.CharField(max_length=1000)),
                ('fabric_xiv', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Hmcs',
            fields=[
                ('hmc_public_ip', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('hmc_ip_ping', models.BooleanField(default=False)),
                ('hmc_credentials', models.CharField(max_length=200)),
                ('hmc_squad', models.CharField(default='POOL', max_length=200)),
                ('hmc_owner', models.CharField(max_length=200)),
                ('hmc_serial', models.CharField(max_length=200)),
                ('hmc_location', models.CharField(max_length=200)),
                ('hmc_private_ip', models.CharField(max_length=200)),
                ('hmc_private_credentials', models.CharField(max_length=200)),
                ('hmc_public_private', models.CharField(max_length=200)),
                ('hmc_imm_ip', models.CharField(max_length=200)),
                ('hmc_mtms', models.CharField(max_length=200)),
                ('hmc_imm_credentials', models.CharField(max_length=200)),
                ('hmclab', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HostGroups',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('descreption', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('cec_fsp_bmc_ip', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('cec_ip_ping', models.BooleanField(default=False)),
                ('cec_fsp_credentials', models.CharField(max_length=200)),
                ('cec_type', models.CharField(max_length=200)),
                ('cec_squad', models.CharField(default='POOL', max_length=200)),
                ('cec_owner', models.CharField(max_length=200)),
                ('cec_name', models.CharField(max_length=200)),
                ('cec_serial', models.CharField(max_length=200)),
                ('cec_location', models.CharField(max_length=200)),
                ('cec_firmware', models.CharField(max_length=200)),
                ('cec_hmc_ip', models.CharField(max_length=200)),
                ('cec_neo_ip', models.CharField(max_length=200)),
                ('cec_vios1', models.CharField(max_length=200)),
                ('cec_vios2', models.CharField(max_length=200)),
                ('cec_proc_memory', models.CharField(max_length=200)),
                ('cec_model', models.CharField(max_length=200)),
                ('cec_network_ports', models.CharField(max_length=200)),
                ('cec_fabric1', models.CharField(max_length=200)),
                ('cec_fabric2', models.CharField(max_length=200)),
                ('cec_pvlan', models.CharField(default='', max_length=200)),
                ('cec_storages', models.CharField(default='', max_length=1000)),
                ('cec_lab', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkNodes',
            fields=[
                ('network_node_ip', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('network_node_ip_ping', models.BooleanField(default=False)),
                ('credentials', models.CharField(max_length=200)),
                ('x_ppc', models.CharField(max_length=20)),
                ('operating_system', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Networks',
            fields=[
                ('vlan_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('subnet_mask', models.CharField(max_length=200)),
                ('gateway', models.CharField(max_length=200)),
                ('dns1', models.CharField(max_length=200)),
                ('dns2', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pvc_Images',
            fields=[
                ('image_volume', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=200)),
                ('storage', models.CharField(max_length=200)),
                ('operating_system', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('ip_add', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=200)),
                ('notify_date', models.DateField()),
                ('notified_today', models.BooleanField(default=False)),
                ('notify_id', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Snapshots',
            fields=[
                ('timestamp', models.DateTimeField(auto_now=True, primary_key=True, serialize=False)),
                ('filepath', models.CharField(max_length=200)),
                ('comments', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Squads',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('descreption', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Storages',
            fields=[
                ('storage_ip', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('storage_ip_ping', models.BooleanField(default=False)),
                ('storage_credentials', models.CharField(max_length=200)),
                ('storage_type', models.CharField(max_length=200)),
                ('storage_port', models.CharField(default=0, max_length=10)),
                ('storage_serial', models.CharField(max_length=200)),
                ('storage_rest_api_server', models.CharField(default=0, max_length=200)),
                ('storage_ldev_id_range', models.CharField(default=0, max_length=200)),
                ('storage_location', models.CharField(max_length=200)),
                ('storage_capacity', models.CharField(max_length=200)),
                ('storage_service_ip', models.CharField(max_length=200)),
                ('storage_lab', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SupportedLevels',
            fields=[
                ('pvc_release', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sld', models.CharField(default='', max_length=1000)),
                ('test_plan', models.CharField(default='', max_length=1000)),
                ('management_node', models.CharField(default='', max_length=1000)),
                ('hmc_level', models.CharField(default='', max_length=1000)),
                ('vios_level', models.CharField(default='', max_length=1000)),
                ('novalink_level', models.CharField(default='', max_length=1000)),
                ('novalink_os', models.CharField(default='', max_length=1000)),
                ('guest_os', models.CharField(default='', max_length=1000)),
                ('storages', models.CharField(default='', max_length=1000)),
                ('comments', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='HostTypes',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('descreption', models.CharField(max_length=200)),
                ('host_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hwt.hostgroups')),
            ],
        ),
    ]
